In [19]:
import numpy as np

array1 = np.array([1, 2, 3])
print(array1, type(array1))
print('array1 array 형태 : ', array1.shape)
print()

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array2, type(array2))
print('array2 array 형태 : ', array2.shape)
print()

array3 = np.array([[1, 2, 3]])
print(array3, type(array3))
print('array3 array 형태 : ', array3.shape)
print()

print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

[1 2 3] <class 'numpy.ndarray'>
array1 array 형태 :  (3,)

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)

[[1 2 3]] <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [6]:
# ndarray 내의 데이터값은 숫자값, 문자열값, 불값 등 모두 가능.
# ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능 -> 한 개의 ndarray의 객체에 int와 float이 공존 불가능.

list1 = [1, 2, 3]
print(type(list))
print()

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'type'>

<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
# 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경한다면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄적용

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
print()

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21

[1. 2. 3.] float64


In [11]:
# ndarray 내 데이터 값의 타입 변경도 astype() 메서드를 이용해 할 수 있다.

array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)
print()

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)
print()

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64

[1 2 3] int32

[1 2 3] int32


In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
print()

zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)

[[0 0]
 [0 0]
 [0 0]]


In [17]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [22]:
array1 = np.arange(10)
print('array1:\n', array1)
print()

array2 = array1.reshape(2, 5)
print('array2:\n', array2)
print()

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5) # -1 인자를 사용하면 나머지 shape 인자에 맞게 생성한다.
print('array2 shape:', array2.shape)
print()
array3 = array1.reshape(5, -1)
print('array3.shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)

array3.shape: (5, 2)


In [25]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) # tolist() 메서드는 ndarray를 리스트 자료형으로 변환할 수 있다.

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [27]:
# 3차원 ndarray를 2차원 ndarray로 변환

array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [29]:
# 1차원 ndarray를 2차원 ndarray로 변환

array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6.shape:', array6.shape)
print(array6)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6.shape: (8, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [34]:
# 1부터 9까지의 1차원 ndarray 생성

array1 = np.arange(start=1, stop=10)
print('array1:', array1)
print()
value = array1[2]
print('value:', value)
print(type(value))
print()
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])
print()
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]

value: 3
<class 'numpy.int64'>

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8

array1: [9 2 3 4 5 6 7 8 0]


In [38]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(-1,3)
print(array2d)
print()
print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [39]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [41]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)
print()

array5 = array1[3:]
print(array5)
print()

array6 = array1[:]
print(array6)

[1 2 3]

[4 5 6 7 8 9]

[1 2 3 4 5 6 7 8 9]


In [47]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)
print()
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print()
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print()
print('array2d[1:3, :] \n', array2d[1:3, :])
print()
print('array2d[:, :] \n', array2d[:, :])
print()
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print()
print('array2d[:2, 0] \n', array2d[:2, 0])
print()
print(array2d[0])
print()
print(array2d[1])
print()
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]

array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]

array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]

array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

array2d[:2, 1:] 
 [[2 3]
 [5 6]]

array2d[:2, 0] 
 [1 4]

[1 2 3]

[4 5 6]

array2d[0] shape: (3,) array2d[1] shape: (3,)


In [50]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())
print()

array4 = array2d[[0, 1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())
print()

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1], 2] => [3, 6]

array2d[[0,1], 0:2] => [[1, 2], [4, 5]]

array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [52]:
# 불린 인덱싱
# 조건 필터링과 검색을 동시에 할 수 있음
# for loop/if else 문보다 훨씬 간단하게 구현 가능
# ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하면 됌

array1d = np.arange(start=1, stop=10)
# []안에 array1d >5 Boolen Indexing을 적용
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)
print()
print(array1d>5)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]

[False False False False False  True  True  True  True]


In [53]:
boolen_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolen_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [54]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


In [60]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
print()
# np.sort()로 정렬 -> 원본 행렬을 수정후 새롭게 반환(?)
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
print()
#ndarray.sort()로 정렬 -> 원본 행렬을 수정(?)
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)
print()
sort_array1_desc = np.sort(org_array)[::-1] # 내림차순 정렬 : [::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

원본 행렬: [3 1 9 5]

np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]

내림차순으로 정렬 : [9 5 3 1]


In [68]:
array2d = np.array([[8, 12],
                   [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('원본 행렬:\n', array2d)
print()
print('row 방향으로 정렬:\n', sort_array2d_axis0)
print()
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('column 방향으로 정렬:\n', sort_array2d_axis1)

원본 행렬:
 [[ 8 12]
 [ 7  1]]

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]

column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [69]:
# 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용한다.

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [72]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [74]:
name_array = np.array(['John', 'Mike', 'Sarah', 'kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'kate']


In [78]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7, 8],
             [9, 10],
             [11, 12]])
dot_product = np.dot(A,B)
print('행렬의 내적 결과:\n', dot_product)

행렬의 내적 결과:
 [[ 58  64]
 [139 154]]


In [81]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [2]:
import pandas as pd

titanic_df = pd.read_csv('examples/datasets/titanic/train.csv')
print('titanic 변수 type:', type(titanic_df))
titanic_df.head()

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
print('columns:', titanic_df.columns)
print('index:', titanic_df.index)
print('index_values:', titanic_df.index.values)

columns: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
index: RangeIndex(start=0, stop=891, step=1)
index_values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 

In [9]:
series = titanic_df['Name'] # series
print(series.head())
print()

filtered_df = titanic_df[['Name', 'Age']] # Dataframe
print(filtered_df.head())

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0


In [3]:
print('DataFrame 크기:', titanic_df.shape)

DataFrame 크기: (891, 12)


In [4]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [11]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [14]:
value_counts = titanic_df['Pclass'].value_counts() 
# value_counts()는 Series 객체에서만 호출가능-> DataFrame에서 단일 column 입력해야함
print(value_counts)
print()
print(type(value_counts))

3    491
1    216
2    184
Name: Pclass, dtype: int64

<class 'pandas.core.series.Series'>


In [17]:
titanic_df.sort_values(by='Pclass')

PassengerId  Survived  Pclass  \
445          446         1       1   
310          311         1       1   
309          310         1       1   
307          308         1       1   
306          307         1       1   
..           ...       ...     ...   
379          380         0       3   
381          382         1       3   
382          383         0       3   
371          372         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
445                          Dodge, Master. Washington    male   4.0      0   
310                     Hays, Miss. Margaret Bechstein  female  24.0      0   
309                     Francatelli, Miss. Laura Mabel  female  30.0      0   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1   
306                            Fleming, Miss. Margaret  female   NaN      0   
..                                                 ...     ...   ...    ...   
379                        Gustafsson, Mr. Karl Gideon    male  19.0      0   
381                        Nakid, Miss. Maria ("Mary")  female   1.0      0   
382                                 Tikkanen, Mr. Juho    male  32.0      0   
371                          Wiklund, Mr. Jakob Alfred    male  18.0      1   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch             Ticket      Fare Cabin Embarked  
445      2              33638   81.8583   A34        S  
310      0              11767   83.1583   C54        C  
309      0           PC 17485   56.9292   E36        C  
307      0           PC 17758  108.9000   C65        C  
306      0              17421  110.8833   NaN        C  
..     ...                ...       ...   ...      ...  
379      0             347069    7.7750   NaN        S  
381      2               2653   15.7417   NaN        C  
382      0  STON/O 2. 3101293    7.9250   NaN        S  
371      0            3101267    6.4958   NaN        S  
890      0             370376    7.7500   NaN        Q  

[891 rows x 12 columns]

In [25]:
col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)

print('array1 shape:', array1.shape)
print()

df_list1 = pd.DataFrame(list1, columns = col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)
print()

df_array1 = pd.DataFrame(array1, columns = col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)

1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3

1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [26]:
col_name2 = ['col1', 'col2', 'col3']
list2 = [[1, 2, 3],
        [11, 12, 13]]
array2 = np.array(list2)

print('array2 shape:', array2.shape)
print()

df_list2 = pd.DataFrame(list2, columns = col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
print()

df_array2 = pd.DataFrame(array2, columns = col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)

2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13

2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [27]:
# key는 column명으로 mapping,Value는 list형(또는 ndarray)

dict = {'col1':[1, 11], 'col2' : [2, 22], 'col3' : [3, 33]}
df_dict = pd.DataFrame(dict)
print('Dictionary로 만든 DataFrame:\n', df_dict)

Dictionary로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [31]:
# DataFrame -> ndarray
array3 = df_dict.values
print('df_dct.values 타입:', type(array3), 'df_dict.values.shape:', array3.shape)
print()
print(array3)

df_dct.values 타입: <class 'numpy.ndarray'> df_dict.values.shape: (2, 3)

[[ 1  2  3]
 [11 22 33]]


In [32]:
# DataFrame 내 새로운 column 생성

titanic_df['Age_0'] = 0
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0  
3      0            113803  53.1000  C123        S      0  
4      0            373450   8.0500   NaN        S      0

In [33]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] +1
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   
3      0            113803  53.1000  C123        S      0      350.0   
4      0            373450   8.0500   NaN        S      0      350.0   

   Family_No  
0          2  
1          2  
2          1  
3          2  
4          1

In [36]:
# 기존 column에 있는 값 업데이트

titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   
3      0            113803  53.1000  C123        S      0      450.0   
4      0            373450   8.0500   NaN        S      0      450.0   

   Family_No  
0          2  
1          2  
2          1  
3          2  
4          1

In [38]:
# (default) axis = 0 : row, axis = 1 : column

titanic_drop_df = titanic_df.drop('Age_0', axis =1)
titanic_drop_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  
0      0         A/5 21171   7.2500   NaN        S      320.0          2  
1      0          PC 17599  71.2833   C85        C      480.0          2  
2      0  STON/O2. 3101282   7.9250   NaN        S      360.0          1  
3      0            113803  53.1000  C123        S      450.0          2  
4      0            373450   8.0500   NaN        S      450.0          1

In [39]:
# inplace = True 옵션을 추가하지 않았으므로 원본 데이터엔 'Age_0' column 존재

titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      320.0   
1      0          PC 17599  71.2833   C85        C      0      480.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      360.0   
3      0            113803  53.1000  C123        S      0      450.0   
4      0            373450   8.0500   NaN        S      0      450.0   

   Family_No  
0          2  
1          2  
2          1  
3          2  
4          1

In [40]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis = 1, inplace= True)
print('inplace = True로 drop 후 반환된 값:', drop_result)
titanic_df.head()

inplace = True로 drop 후 반환된 값: None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [48]:
# 원본 파일 재로딩
titanic_df = pd.read_csv('examples/datasets/titanic/train.csv')

# Index 객체 추출
indexes = titanic_df.index
print(indexes)
print()

# Index 객체를 실제 값 array로 변환
print('Index 객체 array 값:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)

Index 객체 array 값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 2

In [50]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
6


In [51]:
# index 객체는 함부로 변경 불가능

indexes[0] = 5

TypeError: Index does not support mutable operations

In [52]:
series_fair = titanic_df['Fare']
series_fair.head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [61]:
print('Fair Series max 값:', series_fair.max())
print()
print('Fair Series sum 값:', series_fair.sum())
print()
print('sum() Fair Series:', sum(series_fair))
print()
print('Fair Series +3:\n',(series_fair+3).head())

Fair Series max 값: 512.3292

Fair Series sum 값: 28693.9493

sum() Fair Series: 28693.949299999967

Fair Series +3:
 0    10.2500
1    74.2833
2    10.9250
3    56.1000
4    11.0500
Name: Fare, dtype: float64


In [69]:
# ix[] : 명칭 기반과 위치 기반 인덱싱을 함께 제공
# loc[] : 명칭 기반 인덱싱 ex) column명
# iloc[] : 위치 기반 인덱싱 ex) 행, 열 위치값(정수)
# Boolean Indexing : 위치기반, 명칭기반 인덱싱 필요없이 조건식을 []안에 기입해서 간편하게 필터링 수행

titanic_df = pd.read_csv('examples/datasets/titanic/train.csv')
print('단일 컬럼 데이터 추출:₩n', titanic_df['Pclass'].head())
print('₩n여러 컬럼들의 데이터 추출:₩n', titanic_df[['Survived', 'Pclass']].head())

단일 컬럼 데이터 추출:₩n 0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64
₩n여러 컬럼들의 데이터 추출:₩n    Survived  Pclass
0         0       3
1         1       1
2         1       3
3         1       1
4         0       3


In [73]:
data = {'Name' : ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
       'Year' : [2011, 2016, 2015, 2015],
       'Gender' : ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index = ['one', 'two', 'trhee', 'four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
trhee  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [80]:
data_df_reset = data_df.reset_index() # 기존 인덱스를 컬럼으로 변경
data_df_reset = data_df_reset.rename(columns = {'index' : 'old_index'})

# index 값에 1을 더해서 1부터 시작하는 새로운 index 값 생성
data_df_reset.index = data_df_reset.index +1
data_df_reset

old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     trhee  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [81]:
data_df.head()

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
trhee  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [82]:
data_df.iloc[0,0]

'Chulmin'

In [83]:
data_df.iloc[0]

Name      Chulmin
Year         2011
Gender       Male
Name: one, dtype: object

In [87]:
# iloc[] : 위치기반이기 때문에 아래 코드는 오류 발생
data_df.iloc[1, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [90]:
data_df.loc['one','Name']

'Chulmin'

In [91]:
data_df_reset.loc[1, 'Name']
# index는 명칭기반이기 때문에 가능

'Chulmin'

In [97]:
# Boolean Indexing

titanic_df = pd.read_csv('examples/datasets/titanic/train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] >60]
print(type(titanic_boolean))
titanic_boolean.head(10)

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch      Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0  C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1      113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0    PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0      370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0      111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0      113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0       13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0      336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0      345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4       19950  263.0000  C23 C25 C27        S

In [98]:
titanic_df['Age'] > 60

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [100]:
var1 = titanic_df['Age'] > 60
type(var1) # boolean값을 가지는 Sereies 객체

pandas.core.series.Series

In [101]:
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [102]:
titanic_df[['Name', 'Age']][titanic_df['Age']>60].head(3)

Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [104]:
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)
          &(titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [105]:
# 가독성 향상!

cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'
titanic_df[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [106]:
# Aggregation
## Aggregation 함수에서는 axis=0 -> row 이고 axis=1 -> column 이지만
## axis=0 은 column을 계산하고 axis=1 row를 계산한다
titanic_df.count() # NaN 값은 제외

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [108]:
titanic_df[['Age', 'Fare']].mean(axis=0)

Age     29.699118
Fare    32.204208
dtype: float64

In [109]:
titanic_df[['Age', 'Fare']].mean(axis=1)

0      14.62500
1      54.64165
2      16.96250
3      44.05000
4      21.52500
         ...   
886    20.00000
887    24.50000
888    23.45000
889    28.00000
890    19.87500
Length: 891, dtype: float64

In [110]:
titanic_df[['Age', 'Fare']].sum(axis=0)

Age     21205.1700
Fare    28693.9493
dtype: float64

In [111]:
# DataFrame에 groupby()를 호출하면 DataFrameGroupBy 객체를 반환
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))
print(titanic_groupby)

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [112]:
# DAtaFrameGroupBy 객체에 Aggregation함수를 호출하여 Groupby 수행
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass                                                                                    
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [113]:
print(type(titanic_groupby))
print(titanic_groupby.shape)
print(titanic_groupby.index)

<class 'pandas.core.frame.DataFrame'>
(3, 11)
Int64Index([1, 2, 3], dtype='int64', name='Pclass')


In [114]:
titanic_groupby = titanic_df.groupby(by='Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [115]:
# 위 코드와 동일한 결과

titanic_df[['Pclass', 'PassengerId', 'Survived']].groupby('Pclass').count()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [116]:
print(titanic_df.groupby('Pclass')['Pclass'].count())
print()
print(titanic_df['Pclass'].value_counts())

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [117]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [119]:
# 개별적 Aggregation 함수 적용

agg_format = {'Age' : 'max', 'SibSp' : 'sum', 'Fare' : 'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [120]:
# 결손 데이터(Missing Data) 처리하기
## isna() : 주어진 column 값들이 NaN인지 True/False를 반환한다.(NaN이면 True)
## fillna() : Missing Data를 인자로 주어진 값으로 대체

In [121]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [122]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head()

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S
3            4         1       1  Futrelle, M...  female  35.0      1      0          113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450   8.0500  C000        S

In [123]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [124]:
def get_squared(a):
    return a **2

print('3의 제곱은:', get_squared(3))

3의 제곱은: 9


In [125]:
lambda_square = lambda x: x**2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9


In [127]:
a = [1, 2, 3]
squares = map(lambda x: x**2, a)
list(squares)

[1, 4, 9]

In [129]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

In [133]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x:'Child' if x <=15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [137]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else ('Adult' if x <=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [140]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성

def get_category(age):
    cat = ''
    if age<=5: cat = 'Baby'
    elif age <=12: cat = 'Child'
    elif age <=18: cat = 'Teenager'
    elif age <=25: cat = 'student'
    elif age <=35: cat = 'Young Adult'
    elif age <=60: cat = 'Adult'
    else : cat = 'Elderly'
        
    return cat
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age', 'Age_cat']].head()

Age      Age_cat
0  22.0      student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult

In [141]:
# Summary
## 머신러닝 : 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법을 통칭
## 시각화 툴은 matplotlib보단 seaborn 추천